// <auto-generated />
namespace DependencyScopeTracingDisposeBug.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SP_GetRequestBeginEndLogRecords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SP_GetRequestBeginEndLogRecords));
        
        string IMigrationMetadata.Id
        {
            get { return "201301130042495_SP_GetRequestBeginEndLogRecords"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
